# Site
repository: paduk-dev/paduk-dev.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김주성 (KIM Jusung)
title: C# Programmer
email: paduk.dev@gamil.com
phone : 010-5555-4331

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: paduk.dev
instagram_username: paduk._.zzz
# linkedin_username: linkedin
# youtube_username: youtube
# stackoverflow_username: stackoverflow
# twitter_username: twitter
# dribbble_username: dribbble
# facebook_username: facebook
# flickr_username: flickr
# xing_username: xing
# pinterest_username: pinterest
# googleplus_username: +googleplus
# orcid_username: 0000-0000-0000-0000

# Additional icon links

#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: 특허
    layout: text
    content:
      Precast Concrete 공법의 건물 설계 도면 자동 생성 시스템 및 이의 실행 방법 (KR 10-2024-0041595)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: 연우피씨엔지니어링
        link: http://www.yunwoopc.co.kr/
        link_text: yunwoopc.co.kr
        sub_title: 개발팀 - 대리
        caption: 2022. 08. ~ 2024. 05.
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: 빔피어스
        link: https://bimpeers.com/
        link_text: bimpeers.com
        sub_title: 솔루션 2팀 - 주임
        caption: 2020. 04. ~ 2022. 03.
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: 마인드원
        link: http://mind-one.co.kr/
        link_text: mind-one.co.kr
        sub_title: BA 1팀 - 사원
        caption: 2018. 10. ~ 2020. 01.
        quote: >
          상수도 관망 운영과 하수도 모니터링으로 실시간 제어와 유지 관리 최적화를 통한 물 관리 솔루션
        description: |
            Every.

      - layout: left
        title: 녹원정보기술
        link: https://rockwonitglobal.com/
        link_text: rockwonitglobal.com
        sub_title: 개발 2팀 - 사원
        caption: 2018. 06. ~ 2018. 09.
        quote: >
          디지털 트윈 기술을 항만 물류 시스템에 적용하여 실시간 모니터링과 예측 최적화로 물류 효율을 극대화한 스마트 항만 솔루션
        description: |
          디지털 트윈을 활용한 스마트 항만 솔루션은 항만 물류의 효율을 높이는 데 중점을 둔 기술입니다.
          이 솔루션은 항만 운영 환경을 가상으로 재현해 실시간 모니터링과 물류 흐름의 통합 관리를 가능하게 합니다.
          저 또한 이 기술을 통해 항만 운영 환경을 가상으로 재현하고 물류 흐름을 실시간으로 모니터링하는 방법을 배웠으나, 아직은 개념을 이해하는 단계에 머물러 있습니다.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
